### ISSUE TITLE
Particles are merged with words.

### ISSUE THREAD

**Issue by languagedan** [magicsgram/JapaneseSpacer#1]
First off, thank you for the tool!

I noticed that particles (を、は、etc.), auxiliary verbs (する, etc.), etc. are not segmented  out. For example:

ＩＴ　研修　サービスを　比較する　ポイントは

Is this on purpose? Any plans to separate them out in future releases?

Thanks

--Daniel

**Comment by magicsgram** [comment]
> Is this on purpose? Any plans to separate them out in future releases?

No, I rely 100% on whatever Microsoft shipped w/ their Windows 10 Japanese localization library.
There is zero language knowledge involved in making this. (That's why the program is less 20kb)

Although letters like を、は are (usually) usually particles if at the end of a word, inserting a space just based on that rule wouldn't be very accurate. Same goes for auxiliary verbs.
There needs to be more elaborate rules based on language skills and grammar, which I do not know.

By the way, I haven't seen any spaces before particles and auxiliary verbs in my elementary Japanese textbooks. But that could be because my textbooks were intended for Koreans
I'm a Korean native, and Korean language share 90% grammar structure w/ Japanese, but Korean put spaces in all our writings and we do not put spaces in front of particles and auxiliary verbs either. So, I didn't think this was weird in any ways, but I certainly understand it could help a lot for people w/ different mother tongues. 

If there's some very easy-to-use libraries that do more robust spacing like that, I'll be happy to integrate that.
